### PR TITLE
Release preparation

### PR DESCRIPTION
**Pull request by finwo**
Issue: #190 

- Updated all dependencies
- Followed [level-ws/upgrading.md](https://github.com/Level/level-ws/blob/HEAD/UPGRADING.md) to get tests to pass again
- Removed broken badges from readme
- Bumped version to 3.0.0 (no tag, will have to be created manually)
- Fixed logo url in readme for npm
- Github actions now run upon a pull-request as well.

### CODE REVIEW

**Comment by mcollina** [comment]
It didn't seem CI run for these changes.

**Comment by finwo** [comment]
Fair point, it only seems to run on the master branch.

I'll fix that in a separate PR, after which I'll add an empty commit here to trigger CI

**Comment by finwo** [comment]
Found the issue, added another trigger (on pull requests) to the workflow file.

#193 Showed the changes did not need to be merged into master for the actions to be triggered, making another PR unneeded.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Good work!

**Comment by mcollina** [comment]
go ahead, land and npm publish this!

**Comment by mcollina** [comment]
Don't forget to create a a release in github.

**Pull request merged**
